import type {Metadata} from "next";
import localFont from "next/font/local";
import {ReactNode} from "react";
import {Navbar} from "@/components";
import {getSession} from "@/lib/session/session";
import {SessionProvider} from "@/lib/session/SessionContext";
import './globals.css'

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: ReactNode;
}>) {
    const initialSession = await getSession();

    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
                <SessionProvider initialSession={initialSession}>
                    <Navbar/>
                    {children}
                </SessionProvider>
            </body>
        </html>
    );
}