import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import {Navbar} from "@/components";
import {getSession} from "@/lib/session/session";
import {refreshAccessToken} from "@/lib/utils/auth";

async function initializeAuth() {
    const session = await getSession()
    if (session?.refreshToken) {
        await refreshAccessToken(session.refreshToken)
    }
}

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    // await initializeAuth()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Navbar/>
        {children}
      </body>
    </html>
  );
}
